### ISSUE TITLE
ntpd not enabled and started at boot

### ISSUE THREAD

**Issue by graham1228** [digitalrebar/sledgehammer#14]
As a user of the sledgehammer image I would like the time to be auto synced at boot with the time source presented from the DHCP server.

The `ntpd` service isn't being started at boot. It looks like the line for the ntp server is getting placed in `/etc/ntp.conf` but the time isn't getting synced because the `ntpd` service never gets started.

This is problematic for things that require the time be correct such as certs that are generated for the KRIB pattern. You can't necessarily rely on the BIOS time to be correct on bare metal servers.

I'm thinking maybe a line here needs to be added
https://github.com/digitalrebar/sledgehammer/blob/master/sledgehammer.ks#L138

`systemctl enable ntpd`

**Comment by sygibson** [comment]
@graham1228 thank you for the report - we are looking in to this ...  For temporary use you can quickly add a new Stage  with a Task that has an embedded Template in it that makes the `systemctl enable ntpd` call.  Place that prior to your KRIB workflow pieces so NTP is started. 

Long term - we are working on a more fully features NTP service process that will manage the NTP configuration (specifically servers to connect to).  Many of our customers require customizations to support local services as opposed to public Internet facing services (eg 0.pool.ntp.org ... etc).

**Comment by sygibson** [comment]
Stop gap measure:  Simple content pack below that will start NTPD services.  It does NOT attempt to configure `/etc/ntp.conf` - so the context usage for this is Sledgehammer with public NTP pool servers, unless you explicitely overwrite the config file prior to calling this.  A larger NTP service management content pack is on it's way from RackN within the next week or so. 

For the below - save the text as a filename (eg `/tmp/ntpd-start.yaml`), then do:

`drpcli contents create /tmp/ntpd-start.yaml`

```
meta:
  Description: Issues 'systemctl ntpd start' command
  Name: ntpd-start
  Source: Digital Rebar Community Content
  Type: dynamic
  Version: v0.0.1
sections:
  stages:
    ntpd-start:
      Available: false
      BootEnv: ""
      Description: Simple stage to issue a 'systemctl enable ntpd && systemctl start
        ntpd'
      Documentation: "This stage enables and starts NTP services.  It does NOT manage
        the\nNTP service configuration file.  If you need to make changes to the\nconfiguration
        file, please use the larger 'chrony-time' content \npack that supports full
        customizations.\n"
      Errors: []
      Meta:
        color: blue
        icon: clock
        title: Digital Rebar Community Content
      Name: ntpd-start
      OptionalParams: []
      Profiles: []
      ReadOnly: true
      Reboot: false
      RequiredParams: []
      RunnerWait: true
      Tasks:
      - ntpd-start
      Templates: []
      Validated: false
  tasks:
    ntpd-start:
      Available: false
      Description: Simple stage to issue a 'systemctl enable ntpd && systemctl start
        ntpd'
      Documentation: |
        This stage enables and starts NTP services.  It does NOT manage the
        NTP service configuration file.  If you need to make changes to the
        configuration file, please use the larger 'chrony-time' content
        pack that supports full customizations.
      Errors: []
      Meta:
        color: blue
        feature-flags: sane-exit-codes
        icon: clock
        title: Digital Rebar Community Content
      Name: ntpd-start
      OptionalParams: []
      ReadOnly: true
      RequiredParams: []
      Templates:
      - Contents: |
          #!/usr/bin/env bash
          echo ">>> Attempting to start NTP services ... "
          set -x
          set -e
          SERVER=$(grep "^server" /etc/ntp.conf | head -1 | awk ' { print $2 } ')
          ntpdate $SERVER
          systemctl enable ntpd
          systemctl start ntpd
          exit 0
        ID: ""
        Name: ntpd-start
        Path: ""
      Validated: false
```

**Comment by galthaus** [comment]
I'm not going to fix this here.  The repo is not used anymore.  I'll pull this into the new sledgehammer builder and pick it up next time I build sledgehammer.
